version: "3.1"

services:
  api:
    container_name: publish-engine-api
    build:
      context: '.'
      dockerfile: ./Dockerfile.dev
    ports:
      - 4000:4000
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src:cached
  migrations:
    container_name: publish-engine-migrations
    build:
      context: '.'
      dockerfile: ./Dockerfile.dev
    depends_on:
      - db
    command: sh -c "/scripts/wait-for-it.sh db:3306 -- yarn migrate:dev"
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src:cached
      - ./scripts:/scripts/:cached


  db:
    image: mariadb
    restart: always
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: "${MYSQL_ROOT_USER}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "publishing_engine"
    volumes:
      - ./sqldb/data:/var/lib/mysql
      - ./sqldb/scripts:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
