version: "3.1"

services:
  server:
    build:
      dockerfile: ./Dockerfile.dev
    ports:
      - 4000:4000
    restart: always
    container_name: server
    env_file:
      - ./.env
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mariadb
    restart: always
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: "${MYSQL_ROOT_USER}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "publishing_engine_dev"
    volumes:
      - ./sqldb:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
